[package]
name = "skip_ratchet"
version = "0.1.6"
edition = "2021"
description = "Skip ratchet"
keywords = ["wnfs", "webnative", "skip-ratchet", "decentralisation"]
categories = [
  "filesystem",
  "cryptography",
]
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha3 = "=0.10.0"
hex = "=0.4.3"
rand = "=0.6.3"
base64 = "=0.13.0"
serde = { version = "1.0", optional = true, features = ["derive"] }

[features]
serde = ["dep:serde"]

[dev-dependencies]
proptest = "1.0.0"
test-strategy = "0.2.0"

[profile.test]
opt-level = 3
overflow-checks = false
